ODataBookStore/ODataBookStoreWebClient/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using ODataBookStore.Models;
using System.Net.Http.Headers;

namespace ODataBookStoreWebClient.Controllers
{
    public class LoginController : Controller
    {
        private readonly HttpClient client = null;

        private readonly string AccountLoginApiUrl = "";
        private readonly string AccountRegisterApiUrl = "";

        private readonly string UserLoginApiUrl = "";
        private readonly string UserRegisterApiUrl = "";

        public LoginController()
        {
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);


            AccountLoginApiUrl = "https://localhost:44319/Account/Login?";
            AccountRegisterApiUrl = "https://localhost:44319/Account/Register?";

            UserLoginApiUrl = "https://localhost:44319/User/Login?";
            UserRegisterApiUrl = "https://localhost:44319/User/Register?";
        }

        public async Task<IActionResult> Index()
        {
            return View("~/Views/Login/Index.cshtml");
        }

        public async Task<IActionResult> AccountLogin(string username, string password)
        {
            //https://localhost:44319/Account/Login?username=string&password=string

            HttpResponseMessage response 
                = await client.PostAsync("https://localhost:44319/Account/Login?username=" + $"{Uri.EscapeDataString(username)}" + "&password=" + $"{Uri.EscapeDataString(password)}", null);
            
            if (response != null)
            {
                string strData = await response.Content.ReadAsStringAsync();
                TempData["UserData"] = strData;

                return RedirectToAction("", "Book");
            }
            return View("../Login/Index");
        }

    }
}

ODataBookStore/ODataBookStoreWebClient/Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using ODataBookStore.Models;
using System.Net.Http.Headers;

namespace ODataBookStoreWebClient.Controllers
{
    public class SignUpController : Controller
    {
        private readonly HttpClient client = null;

        public SignUpController()
        {
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
        }

        public IActionResult Index()
        {
            return View("~/Views/Login/SignUp.cshtml");
        }

        public async Task<IActionResult> SignUp(string username, string password, int roleId)
        {
            HttpResponseMessage response
                = await client.PostAsync("https://localhost:44319/Account/Register?username=" + $"{Uri.EscapeDataString(username)}" + "&password=" + $"{Uri.EscapeDataString(password)}" + "&roleId=" + $"{roleId}", null);
            if(response.IsSuccessStatusCode)
            {
                return View("~/Views/Login/Index.cshtml");
            }
            return View();
        }
    }
}

ODataBookStore/ODataBookStoreWebClient/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login Page";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Facebook-Login or Sign up</title>
    <!-- <link rel="stylesheet" href="style2.css"> -->

    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f0f2f5;
            color: #1c1e21;
        }

        main {
            height: 90vh;
            width: 50vw;
            position: relative;
            margin: 0 auto;
        }

        footer {
            height: 10vh;
            background-color: #ffffff;
        }

        .row {
            display: flex;
            justify-content: space-around;
            align-items: center;
            width: 100%;
            max-width: 1000px;
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }

        .colm-logo {
            flex: 0 0 50%;
            text-align: left;
        }

        .colm-form {
            flex: 0 0 40%;
            text-align: center;
        }

        .colm-logo img {
            max-width: 400px;
        }

        .colm-logo h2 {
            font: 26px;
            font-weight: 400;
            padding: 0 30px;
            line-height: 32px;
        }

        .colm-form .form-container {
            background-color: #ffffff;
            border: none;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1), 0 8px 16px rgba(0, 0, 0, 0.1);
            margin-bottom: 30px;
            padding: 20px;
            max-width: 400px;
        }

            .colm-form .form-container input, .colm-form .form-container .btn-login {
                width: 100%;
                margin: 5px 0;
                height: 45px;
                vertical-align: middle;
                font-size: 16px;
            }

            .colm-form .form-container input {
                border: 1px solid #dddfe2;
                color: #1d2129;
                padding: 0 8px;
                outline: none;
            }

                .colm-form .form-container input:focus {
                    border-color: #1877f2;
                    box-shadow: 0 0 0 2px #e7f3ff;
                }

            .colm-form .form-container .btn-login {
                background-color: #1877f2;
                border: none;
                border-radius: 6px;
                font-size: 20px;
                padding: 0 16px;
                color: #ffffff;
                font-weight: 700;
            }

            .colm-form .form-container a {
                display: block;
                color: #1877f2;
                font-size: 14px;
                text-decoration: none;
                padding: 10px 0 20px;
                border-bottom: 1px solid #dadde1;
            }

                .colm-form .form-container a:hover {
                    text-decoration: underline;
                }

            .colm-form .form-container .btn-new {
                background-color: #42b72a;
                border: none;
                border-radius: 6px;
                font-size: 17px;
                line-height: 48px;
                padding: 0 16px;
                color: #ffffff;
                font-weight: 700;
                margin-top: 20px;
            }

        .colm-form p {
            font-size: 14px;
        }

            .colm-form p a {
                text-decoration: none;
                color: #1c1e21;
                font-weight: 600;
            }

                .colm-form p a:hover {
                    text-decoration: underline;
                }

        .footer-contents {
            position: relative;
            max-width: 1000px;
            margin: 0 auto;
        }

        footer ol {
            display: flex;
            flex-wrap: wrap;
            list-style-type: none;
            padding: 10px 0;
        }

            footer ol:first-child {
                border-bottom: 1px solid #dddfe2;
            }

                footer ol:first-child li:last-child button {
                    background-color: #f5f6f7;
                    border: 1px solid #ccd0d5;
                    outline: none;
                    color: #4b4f56;
                    padding: 0 8px;
                    font-weight: 700;
                    font-size: 16px;
                }

            footer ol li {
                padding-right: 15px;
                font-size: 12px;
                color: #385898;
            }

                footer ol li a {
                    text-decoration: none;
                    color: #385898;
                }

                    footer ol li a:hover {
                        text-decoration: underline;
                    }

        footer small {
            font-size: 11px;
        }
    </style>
</head>
<body>
    <main>
        <div class="row">
            <div class="colm-logo">
                <img style="margin: 30px" src="https://nordicapis.com/wp-content/uploads/odata-open-data-protocol-300x140.jpg" alt="Logo">
                <br /><br />
                <h2>PRN231 helps you connect and share with the people in your life.</h2>
            </div>
            <div class="colm-form">
                <div class="form-container">
                    <form asp-controller="Login" asp-action="AccountLogin" method="post">
                    <input type="text" id="username" name="username" placeholder="Email address or phone number" required>
                    <input type="password" id="password" name="password" placeholder="Password" required>
                    <button class="btn-login" type="submit">Login</button>

                    <a asp-controller="SignUp" class="btn-new">Create new Account</a>
                    </form>
                </div>
                <div class="signin">
                    Don't have an account? <a asp-controller="SignUp">Sign up</a>
                </div>
            </div>
        </div>
    </main>
</body>
</html>

ODataBookStore/ODataBookStoreWebClient/Views/Login/SignUp.cshtml
@{
    ViewData["Title"] = "SignUp";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Facebook-Login or Sign up</title>
    <!-- <link rel="stylesheet" href="style2.css"> -->

    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f0f2f5;
            color: #1c1e21;
        }

        main {
            height: 90vh;
            width: 50vw;
            position: relative;
            margin: 0 auto;
        }

        footer {
            height: 10vh;
            background-color: #ffffff;
        }

        .row {
            display: flex;
            justify-content: space-around;
            align-items: center;
            width: 100%;
            max-width: 1000px;
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }

        .colm-logo {
            flex: 0 0 50%;
            text-align: left;
        }

        .colm-form {
            flex: 0 0 40%;
            text-align: center;
        }

        .colm-logo img {
            max-width: 400px;
        }

        .colm-logo h2 {
            font: 26px;
            font-weight: 400;
            padding: 0 30px;
            line-height: 32px;
        }

        .colm-form .form-container {
            background-color: #ffffff;
            border: none;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1), 0 8px 16px rgba(0, 0, 0, 0.1);
            margin-bottom: 30px;
            padding: 20px;
            max-width: 400px;
        }

            .colm-form .form-container input, .colm-form .form-container .btn-login {
                width: 100%;
                margin: 5px 0;
                height: 45px;
                vertical-align: middle;
                font-size: 16px;
            }

            .colm-form .form-container input {
                border: 1px solid #dddfe2;
                color: #1d2129;
                padding: 0 8px;
                outline: none;
            }

                .colm-form .form-container input:focus {
                    border-color: #1877f2;
                    box-shadow: 0 0 0 2px #e7f3ff;
                }

            .colm-form .form-container .btn-login {
                background-color: #1877f2;
                border: none;
                border-radius: 6px;
                font-size: 20px;
                padding: 0 16px;
                color: #ffffff;
                font-weight: 700;
            }

            .colm-form .form-container a {
                display: block;
                color: #1877f2;
                font-size: 14px;
                text-decoration: none;
                padding: 10px 0 20px;
                border-bottom: 1px solid #dadde1;
            }

                .colm-form .form-container a:hover {
                    text-decoration: underline;
                }

            .colm-form .form-container .btn-new {
                background-color: #42b72a;
                border: none;
                border-radius: 6px;
                font-size: 17px;
                line-height: 48px;
                padding: 0 16px;
                color: #ffffff;
                font-weight: 700;
                margin-top: 20px;
            }

        .colm-form p {
            font-size: 14px;
        }

            .colm-form p a {
                text-decoration: none;
                color: #1c1e21;
                font-weight: 600;
            }

                .colm-form p a:hover {
                    text-decoration: underline;
                }

        .footer-contents {
            position: relative;
            max-width: 1000px;
            margin: 0 auto;
        }

        footer ol {
            display: flex;
            flex-wrap: wrap;
            list-style-type: none;
            padding: 10px 0;
        }

            footer ol:first-child {
                border-bottom: 1px solid #dddfe2;
            }

                footer ol:first-child li:last-child button {
                    background-color: #f5f6f7;
                    border: 1px solid #ccd0d5;
                    outline: none;
                    color: #4b4f56;
                    padding: 0 8px;
                    font-weight: 700;
                    font-size: 16px;
                }

            footer ol li {
                padding-right: 15px;
                font-size: 12px;
                color: #385898;
            }

                footer ol li a {
                    text-decoration: none;
                    color: #385898;
                }

                    footer ol li a:hover {
                        text-decoration: underline;
                    }

        footer small {
            font-size: 11px;
        }
    </style>
</head>
<body>
    <main>
        <div class="row">
            <div class="colm-logo">
                <img style="margin: 30px" src="https://nordicapis.com/wp-content/uploads/odata-open-data-protocol-300x140.jpg" alt="Logo">
                <br /><br />
                <h2>PRN231 helps you connect and share with the people in your life.</h2>
            </div>
            <div class="colm-form">
                <div class="form-container">
                    <form asp-controller="SignUp" asp-action="SignUp" method="post">
                    <input type="text" id="username" name="username" placeholder="Email address or phone number" required>
                    <input type="password" id="password" name="password" placeholder="Password" required>

                    <input type="radio" id="1" name="roleId" value="1" required>
                    <label for="1">Account</label><br>
                    <button class="btn-login" type="submit">Sign Up</button>
                    </form>
                </div>
                <div class="signin">
                    Already have an account? <a asp-controller="Login">Sign in</a>
                </div>
            </div>
        </div>
    </main>
</body>
</html>